### PR TITLE
Fixes #1100 add support for non-static @Before and @After methods …

### LINKED ISSUE #1100: Add support for non-static @Before and @After methods
Let's say we have controller `MyController` with `@With` annotation:

```java
@With(MySecurity.class)
public class MyController extends Controller {
}

public class MySecurity extends Controller {
  @Before
  public void myNonstaticBeforeMethod() {
  }

  @After
  public void myNonstaticAfterMethod() {
  }
}
```

When trying to execute any action of `MyController`, Play framework throws an exception:

```java
Oops: IllegalArgumentException
Unexpected error : Unexpected Error, caused by exception IllegalArgumentException: object is not an instance of declaring class

play.exceptions.UnexpectedException: Unexpected Error
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:208)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:482)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:467)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:436)
	at play.mvc.ActionInvoker.handleBefores(ActionInvoker.java:299)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:144)
	... 1 more
```

### PR DESCRIPTION
**Pull request by asolntsev**
…in @With class

### CODE REVIEW

File: framework/src/play/mvc/ActionInvoker.java [hunk 1]
```diff
@@ -464,7 +464,11 @@ public static Object invokeControllerMethod(Method method, Object[] forceArgs) t
             }
         }
 
-        return invoke(method, request.controllerInstance, args);
+        Object methodClassInstance = isStatic ? null :
+            (method.getDeclaringClass() == request.controllerClass) ? request.controllerInstance :
```
Comment (xael-fry) [inline framework/src/play/mvc/ActionInvoker.java]: you should use ```.equals()``` instead of ```==```

**Comment by asolntsev** [comment]
@xael-fry Thank you. Implemented your suggestion.
Merged.
